### ISSUE TITLE
pdf to icdar

### ISSUE THREAD

**Issue by ghost** [wusongchao/fast-rcnn-pytorch-pdf-table#1]
@wusongchao Can you create a script that convert pdf words, into icdar like .txt

**Comment by wusongchao** [comment]
@deepseek sorry, but what do you mean? Could you explain it more specifically?

**Comment by ghost** [comment]
Hi man,
I was wondering if you can create a script that can convert fully editable digital pdf files into pairs of
 `jpg + txt` [example output.zip](https://github.com/wusongchao/fast-rcnn-pytorch-pdf-table/files/3607239/example.zip)
Perhaps giving an option of creating boxes of words, or creating boxes of lines.
Boxes are polygon shaped, and have coordinate of `x1,y1,x2,y2,x3,y3,x4,y4`
![example1](https://user-images.githubusercontent.com/49877135/64816646-c0f8c500-d5b0-11e9-94e6-1d1fc62b57d6.jpg)

**Comment by wusongchao** [comment]
@deepseek  That will need a little more code lines than a simple script. As far as i know, you can use PDFBox or iText to achieve your goal. For python, you can do some search by google.

**Comment by deepseek** [comment]
@wusongchao 
I know a way to solve this, are you available to be hired for this job?

**Comment by wusongchao** [comment]
@deepseek no.
